---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library('edgeR')

ATAC_raw <-  read.table("../ATAC_counts/ATAC_counts.txt", header=TRUE)
H3K4me1_raw <-  read.table("../CR_counts/H3K4me1.txt", header=TRUE)
H3K4me3_raw <-  read.table("../CR_counts/H3K4me3.txt", header=TRUE)
H3K27me3_raw <- read.table("../CR_counts/H3K27me3.txt", header=TRUE)
H3K27ac_raw <- read.table("../CR_counts/H3K27ac.txt", header=TRUE)
```

```{r}
ATAC_counts = ATAC_raw[, 7:15]
normFactor_ATAC <- calcNormFactors(object = ATAC_counts, method = "TMM")
LibSize_ATAC <- colSums(ATAC_counts)
SizeFactors_ATAC <- normFactor_ATAC * LibSize_ATAC / 1000000
SizeFactors_ATAC.reciprocal <- 1/SizeFactors_ATAC
SizeFactors_ATAC.reciprocal
```

```{r}
H3K4me1_counts = H3K4me1_raw[, 7:8]
normFactor_H3K4me1 <- calcNormFactors(object = H3K4me1_counts, method = "TMM")
LibSize_H3K4me1 <- colSums(H3K4me1_counts)
SizeFactors_H3K4me1 <- normFactor_H3K4me1 * LibSize_H3K4me1 / 1000000
SizeFactors_H3K4me1.reciprocal <- 1/SizeFactors_H3K4me1
SizeFactors_H3K4me1.reciprocal
```

```{r}
library('edgeR')
H3K4me3_counts = H3K4me3_raw[, 7:8]
normFactor_H3K4me3 <- calcNormFactors(object = H3K4me3_counts, method = "TMM")
LibSize_H3K4me3 <- colSums(H3K4me3_counts)
SizeFactors_H3K4me3 <- normFactor_H3K4me3 * LibSize_H3K4me3 / 1000000
SizeFactors_H3K4me3.reciprocal <- 1/SizeFactors_H3K4me3
SizeFactors_H3K4me3.reciprocal
```

```{r}
H3K27me3_counts = H3K27me3_raw[, 7:8]
normFactor_H3K27me3 <- calcNormFactors(object = H3K27me3_counts, method = "TMM")
LibSize_H3K27me3 <- colSums(H3K27me3_counts)
SizeFactors_H3K27me3 <- normFactor_H3K27me3 * LibSize_H3K27me3 / 1000000
SizeFactors_H3K27me3.reciprocal <- 1/SizeFactors_H3K27me3
SizeFactors_H3K27me3.reciprocal
```

```{r}
H3K27ac_counts = H3K27ac_raw[, 7:8]
normFactor_H3K27ac <- calcNormFactors(object = H3K27ac_counts, method = "TMM")
LibSize_H3K27ac <- colSums(H3K27ac_counts)
SizeFactors_H3K27ac <- normFactor_H3K27ac * LibSize_H3K27ac / 1000000
SizeFactors_H3K27ac.reciprocal <- 1/SizeFactors_H3K27ac
SizeFactors_H3K27ac.reciprocal
```

```{r}
ase_raw <-  read.table("../CR_counts/ase.txt", header=TRUE)
btd_raw <-  read.table("../CR_counts/btd.txt", header=TRUE)
fruC_raw <- read.table("../CR_counts/fruC.txt", header=TRUE)
fruCOM_apkc_raw <- read.table("../CR_counts/fruCOM_aPKC.txt", header=TRUE)
zld_raw <- read.table("../CR_counts/zld.txt", header=TRUE)
zld_apkc_raw <- read.table("../CR_counts/zld_aPKC.txt", header=TRUE)
```

```{r}
ase_counts = ase_raw[, 7:8]
normFactor_ase <- calcNormFactors(object = ase_counts, method = "TMM")
LibSize_ase <- colSums(ase_counts)
SizeFactors_ase <- normFactor_ase * LibSize_ase / 1000000
SizeFactors_ase.reciprocal <- 1/SizeFactors_ase
SizeFactors_ase.reciprocal
```

```{r}
btd_counts = btd_raw[, 7:8]
normFactor_btd <- calcNormFactors(object = btd_counts, method = "TMM")
LibSize_btd <- colSums(btd_counts)
SizeFactors_btd <- normFactor_btd * LibSize_btd / 1000000
SizeFactors_btd.reciprocal <- 1/SizeFactors_btd
SizeFactors_btd.reciprocal
```
```{r}
fruC_counts = fruC_raw[, 7:8]
normFactor_fruC <- calcNormFactors(object = fruC_counts, method = "TMM")
LibSize_fruC <- colSums(fruC_counts)
SizeFactors_fruC <- normFactor_fruC * LibSize_fruC / 1000000
SizeFactors_fruC.reciprocal <- 1/SizeFactors_fruC
SizeFactors_fruC.reciprocal
```

```{r}
fruCOM_apkc_counts = fruCOM_apkc_raw[, 7:8]
normFactor_fruCOM_apkc <- calcNormFactors(object = fruCOM_apkc_counts, method = "TMM")
LibSize_fruCOM_apkc <- colSums(fruCOM_apkc_counts)
SizeFactors_fruCOM_apkc <- normFactor_fruCOM_apkc * LibSize_fruCOM_apkc / 1000000
SizeFactors_fruCOM_apkc.reciprocal <- 1/SizeFactors_fruCOM_apkc
SizeFactors_fruCOM_apkc.reciprocal
```

```{r}
zld_counts = zld_raw[, 7:8]
normFactor_zld <- calcNormFactors(object = zld_counts, method = "TMM")
LibSize_zld <- colSums(zld_counts)
SizeFactors_zld <- normFactor_zld * LibSize_zld / 1000000
SizeFactors_zld.reciprocal <- 1/SizeFactors_zld
SizeFactors_zld.reciprocal
```

```{r}
zld_apkc_counts = zld_apkc_raw[, 7:8]
normFactor_zld_apkc <- calcNormFactors(object = zld_apkc_counts, method = "TMM")
LibSize_zld_apkc <- colSums(zld_apkc_counts)
SizeFactors_zld_apkc <- normFactor_zld_apkc * LibSize_zld_apkc / 1000000
SizeFactors_zld_apkc.reciprocal <- 1/SizeFactors_zld_apkc
SizeFactors_zld_apkc.reciprocal
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(rtracklayer))
suppressPackageStartupMessages(library(GenomicRanges))
              
zscore_bw <- function(bw) {
  require(tidyverse)
  require(rtracklayer)
  require(GenomicRanges)
  
  # import bigwig file to Granges
  if (typeof(bw) == "character") {
    message("reading bigwig file")
    bw <- import(bw)
  }
  
  # for large regions with the same score, expand into equal sized bins
  message("binning genome")
  min_binsize <- min(width(bw))
  all_bins <- tileGenome(seqinfo(bw), tilewidth=min_binsize,cut.last.tile.in.chrom=TRUE)
  
  message("getting scores for all bins")
  # add the coverage/score for both input and IP
  all_bins <- subsetByOverlaps(all_bins, bw)
  overlaps <- findOverlaps(all_bins, bw)
  all_bins$score[overlaps@from] <- bw$score[overlaps@to]
  
  # perform z-score normalization
  message("performing z-score normalization")
  all_bins$zscore <- scale(all_bins$score)[,1]
  all_bins$score <- NULL
  all_bins$score <- all_bins$zscore
  all_bins$zscore <- NULL
  # collapse adjacent bins with same score
  collapsed <- unlist(GenomicRanges::reduce(split(all_bins, ~score)))
  collapsed$score <- as.numeric(names(collapsed))
  names(collapsed) <- NULL
  all_bins <- collapsed
  
  #set seqinfo for z-score normalized version
  seqinfo(all_bins) <- seqinfo(bw)
  
  return(all_bins)
}
```

```{r}
# perform z-score normalization and write new bigwig files for CUT&RUN ---------------------
files <- list.files(path="../bigwigs_CR/TMM_merged", pattern="*.small.bw", full.names=TRUE, recursive=FALSE)
for (f in files){
  print(f)
  out = paste("../bigwigs_CR/z-score_R/",basename(f), sep="")
  zscore.gr <- zscore_bw(f)
  export(zscore.gr, out)
}
files <- list.files(path="../bigwigs_CR/TMM_merged", pattern="*.bw", full.names=TRUE, recursive=FALSE)
for (f in files){
  print(f)
  out = paste("../bigwigs_CR/z-score_R/",basename(f), sep="")
  zscore.gr <- zscore_bw(f)
  export(zscore.gr, out)
}
```

```{r}
files <- list.files(path="../bigwigs_ATAC/TMM_merged", pattern="*.bw", full.names=TRUE, recursive=FALSE)
for (f in files){
  print(f)
  out = paste("../bigwigs_ATAC/z-score_R/",basename(f), sep="")
  zscore.gr <- zscore_bw(f)
  export(zscore.gr, out)
}
```